[package]
name = "cbor_debug"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
minicbor = { version = "0.20", features = ["alloc", "derive"] }